/**
 * This file contains all the includes for the opus audio files, which are in 
 * ogg containers, but then just without the comments header.
 */
#include "audio/pauw opstart geluid.h"
#include "audio/🎵 hallo ik ben een pauw, kom speel je mee met mij want samen zijn met jou, dat maakt me reuze blij.h"
#include "audio/spelen/ben jij ook wel eens verbaasd?.h"
#include "audio/spelen/snavel knop/ik heb de allermooiste veren.h"
#include "audio/spelen/snavel knop/tjilp 2.h"
#include "audio/spelen/snavel knop/ik ben een grote vogel en ik kan goed vliegen.h"
#include "audio/spelen/snavel knop/ik spreid mijn staartveren als een waaier.h"
#include "audio/spelen/snavel knop/ik eet graag planten en insecten.h"
#include "audio/spelen/snavel knop/ik woon in het bos.h"
#include "audio/spelen/snavel knop/tjilp 1.h"
#include "audio/spelen/dit is een vierkant/dit is een vierkant.h"
#include "audio/spelen/dit is een vierkant/blauw.h"
#include "audio/spelen/dit is een vierkant/dit is een blauw vierkant.h"
#include "audio/spelen/dit is een vierkant/blauwe knijper.h"
#include "audio/spelen/ik heb geen knijpers meer op mijn staart.h"
#include "audio/spelen/dit is een hart/gele knijper.h"
#include "audio/spelen/dit is een hart/dit is een geel hart.h"
#include "audio/spelen/dit is een hart/geel.h"
#include "audio/spelen/dit is een hart/dit is een hart.h"
#include "audio/spelen/dit is een ster/dit is een paarse ster.h"
#include "audio/spelen/dit is een ster/paarse knijper.h"
#include "audio/spelen/dit is een ster/paars.h"
#include "audio/spelen/dit is een ster/dit is een ster.h"
#include "audio/spelen/korte geluidseffecten/4.h"
#include "audio/spelen/korte geluidseffecten/1.h"
#include "audio/spelen/korte geluidseffecten/6.h"
#include "audio/spelen/korte geluidseffecten/2.h"
#include "audio/spelen/korte geluidseffecten/5.h"
#include "audio/spelen/korte geluidseffecten/3.h"
#include "audio/spelen/hmm, ik ben een beetje verdrietig, kun jij me opvrolijken?.h"
#include "audio/spelen/groep 1/druk op een toets of plaats een knijper om te spelen.h"
#include "audio/spelen/groep 1/hoi, ik ben een sierlijke pauw, laten we spelen, hoeraa!!.h"
#include "audio/spelen/groep 1/laten we ontdekken en leren, met mijn prachtige veren!.h"
#include "audio/spelen/dit is een driehoek/dit is een driehoek.h"
#include "audio/spelen/dit is een driehoek/rode knijper.h"
#include "audio/spelen/dit is een driehoek/dit is een rode driehoek.h"
#include "audio/spelen/dit is een driehoek/rood.h"
#include "audio/spelen/dankjewel! je hebt me opgevrolijkt!.h"
#include "audio/leren/ik voel me boos! hmm.h"
#include "audio/leren/zoek de ster toets/druk op de paarse ster toets.h"
#include "audio/leren/zoek de ster toets/zoek de paarse toets.h"
#include "audio/leren/zoek de ster toets/druk op de ster toets.h"
#include "audio/leren/zoek de ster toets/kun jij de verbaasde knijper op mijn staart plaatsen?.h"
#include "audio/leren/zoek de ster toets/kun jij de paarse knijper op mijn staart plaatsen?.h"
#include "audio/leren/zoek de ster toets/druk op de paarse toets.h"
#include "audio/leren/zoek de ster toets/zoek de paarse ster toets.h"
#include "audio/leren/zoek de ster toets/zoek de ster toets.h"
#include "audio/leren/alle veren nog aan toe.h"
#include "audio/leren/dan ben ik weer blij!.h"
#include "audio/leren/kun je mij verbazen?.h"
#include "audio/leren/druk op een toets om te beantwoorden.h"
#include "audio/leren/laten we eens kijken of je deze vragen kunt beantwoorden.h"
#include "audio/leren/goed/vierkant toets/geweldig! dit is de vierkant toets.h"
#include "audio/leren/goed/vierkant toets/goed gedaan! dit is de blauwe toets.h"
#include "audio/leren/goed/vierkant toets/goed gedaan! dit is de blauwe vierkant toets.h"
#include "audio/leren/goed/ster toets/dankjewel! ik ben echt verbaasd.h"
#include "audio/leren/goed/ster toets/goed gedaan! dit is de paarse ster toets.h"
#include "audio/leren/goed/ster toets/goed gedaan! dit is de ster toets.h"
#include "audio/leren/goed/ster toets/heel goed! dit is de paarse toets.h"
#include "audio/leren/goed/driehoek toets/goed werk! dit is de driehoek toets.h"
#include "audio/leren/goed/driehoek toets/super! dit is de rode driehoek toets.h"
#include "audio/leren/goed/driehoek toets/fantastisch! dit is de rode toets.h"
#include "audio/leren/goed/hart toets/goed gedaan! dit is de hart toets.h"
#include "audio/leren/goed/hart toets/geweldig! dit is de gele toets.h"
#include "audio/leren/goed/hart toets/dankjewel! dat maakt me blij!.h"
#include "audio/leren/goed/hart toets/geweldig! dit is de gele hart toets.h"
#include "audio/leren/goed/geluid 1.h"
#include "audio/leren/goed/geluid 2.h"
#include "audio/leren/zoek de driehoek toets/zoek de rode toets.h"
#include "audio/leren/zoek de driehoek toets/zoek de rode driehoek toets.h"
#include "audio/leren/zoek de driehoek toets/ik mis mijn rode knijper, kun jij deze asjeblieft op mijn staart plaatsen?.h"
#include "audio/leren/zoek de driehoek toets/druk op de driehoek toets.h"
#include "audio/leren/zoek de driehoek toets/druk op de rode toets.h"
#include "audio/leren/zoek de driehoek toets/druk op de rode driehoek toets.h"
#include "audio/leren/zoek de driehoek toets/zoek de driehoek toets.h"
#include "audio/leren/zoek de driehoek toets/ik zoek de rode knijper, kun jij deze op mijn staart plaatsen?.h"
#include "audio/leren/zoek de vierkant toets/druk op de vierkant toets.h"
#include "audio/leren/zoek de vierkant toets/zoek de blauwe toets.h"
#include "audio/leren/zoek de vierkant toets/zoek de blauwe vierkant toets.h"
#include "audio/leren/zoek de vierkant toets/ik ben op zoek naar de blauwe knijper, kun jij deze op mijn staart plaatsen?.h"
#include "audio/leren/zoek de vierkant toets/druk op de blauwe vierkant toets.h"
#include "audio/leren/zoek de vierkant toets/zoek de vierkant toets.h"
#include "audio/leren/zoek de vierkant toets/zoek de blauwe knijper, kun jij deze op mijn staart plaatsen?.h"
#include "audio/leren/zoek de vierkant toets/druk op de blauwe toets.h"
#include "audio/leren/hmm, ik ben een beetje sip.h"
#include "audio/leren/zoek de hart toets/druk op de hart toets.h"
#include "audio/leren/zoek de hart toets/zoek de gele hart toets.h"
#include "audio/leren/zoek de hart toets/druk op de gele hart toets.h"
#include "audio/leren/zoek de hart toets/ik ben een beetje verdrietig, kun jij een gele knijper op mijn staart plaatsen? dan ben ik weer blij!.h"
#include "audio/leren/zoek de hart toets/druk op de gele toets.h"
#include "audio/leren/zoek de hart toets/zoek de gele toets.h"
#include "audio/leren/zoek de hart toets/zoek de hart toets.h"
#include "audio/leren/zoek de hart toets/ik ben zo blij! kun jij een gele knijper op mijn staart plaatsen?.h"
#include "audio/leren/fout/vierkant toets/we zoeken de vierkant toets.h"
#include "audio/leren/fout/vierkant toets/we zoeken de blauwe toets.h"
#include "audio/leren/fout/vierkant toets/we zoeken de blauwe vierkant toets.h"
#include "audio/leren/fout/ster toets/we zoeken de paarse toets.h"
#include "audio/leren/fout/ster toets/we zoeken de paarse ster toets.h"
#include "audio/leren/fout/ster toets/we zoeken de ster toets.h"
#include "audio/leren/fout/driehoek toets/we zoeken de rode toets.h"
#include "audio/leren/fout/driehoek toets/we zoeken de rode driehoek toets.h"
#include "audio/leren/fout/driehoek toets/we zoeken de driehoek toets.h"
#include "audio/leren/fout/hart toets/we zoeken de hart toets.h"
#include "audio/leren/fout/hart toets/we zoeken de gele hart toets.h"
#include "audio/leren/fout/hart toets/we zoeken de gele toets.h"
#include "audio/leren/fout/kijk naar het knipperende lichtje!.h"
#include "audio/leren/fout/geluid 1.h"
#include "audio/leren/fout/de volgende keer gaat het vast beter!.h"
#include "audio/leren/fout/geluid 2.h"
#include "audio/leren/laten we ontdekken en leren, met mijn prachtige veren!.h"
#include "audio/leren/laten we een andere proberen.h"
#include "audio/klik.h"
#include "audio/muziek/blije muziekjes/muziekje 6.h"
#include "audio/muziek/blije muziekjes/muziekje 5.h"
#include "audio/muziek/wat een verassing!.h"
#include "audio/muziek/verdrietige muziekjes/muziekje 7.h"
#include "audio/muziek/verdrietige muziekjes/muziekje 8.h"
#include "audio/muziek/snavel knop/wil je mij horen zingen?, muziekje 10.h"
#include "audio/muziek/snavel knop/het is tijd om te zingen!, muziekje 9.h"
#include "audio/muziek/🎵 tijd voor muziek! druk op een toets om naar muziek te luisteren.h"
#include "audio/muziek/boze muziekjes/muziekje 3.h"
#include "audio/muziek/boze muziekjes/muziekje 4.h"
#include "audio/muziek/korte geluidseffecten/1.h"
#include "audio/muziek/korte geluidseffecten/2.h"
#include "audio/muziek/ik ben boos!.h"
#include "audio/muziek/ik voel me een beetje verdrietig.h"
#include "audio/muziek/ik ben zo blij!.h"
#include "audio/muziek/verbaasde muziekjes/muziekje 1.h"
#include "audio/muziek/verbaasde muziekjes/muziekje 2.h"
