#ifndef MUXED_GPIO_H
#define MUXED_GPIO_H

#include <stdbool.h>

enum muxed_inputs {
    MUXED_INPUT_MIN = 0, /* 0 */
    MUXED_INPUT_BUTTONS_MIN = MUXED_INPUT_MIN,
    /* Buttons. */
    MUXED_INPUT_STAR_L_BUTTON = MUXED_INPUT_BUTTONS_MIN,
    MUXED_INPUT_TRIANGLE_L_BUTTON,
    MUXED_INPUT_SQUARE_L_BUTTON,
    MUXED_INPUT_HEART_L_BUTTON,
    MUXED_INPUT_HEART_R_BUTTON,
    MUXED_INPUT_SQUARE_R_BUTTON,
    MUXED_INPUT_TRIANGLE_R_BUTTON,
    MUXED_INPUT_STAR_R_BUTTON,
    
    MUXED_INPUT_BUTTONS_MAX = MUXED_INPUT_STAR_R_BUTTON, /* 7 */
    
    MUXED_INPUT_N_BUTTONS, /* 8 */
    MUXED_INPUT_CLIPS_MIN = MUXED_INPUT_N_BUTTONS,
    /* Clips. */
    MUXED_INPUT_STAR_L_CLIP = MUXED_INPUT_CLIPS_MIN,
    MUXED_INPUT_TRIANGLE_L_CLIP,
    MUXED_INPUT_SQUARE_L_CLIP,
    MUXED_INPUT_HEART_L_CLIP,
    MUXED_INPUT_HEART_R_CLIP,
    MUXED_INPUT_SQUARE_R_CLIP,
    MUXED_INPUT_TRIANGLE_R_CLIP,
    MUXED_INPUT_STAR_R_CLIP,
    
    MUXED_INPUT_CLIPS_MAX = MUXED_INPUT_STAR_R_CLIP, /* 15 */
   
    MUXED_INPUT_SWITCH_MIN,
    /* Switches. */
    MUXED_INPUT_BEAK_SWITCH = MUXED_INPUT_SWITCH_MIN, /* 16 */
    MUXED_INPUT_LEARN_SWITCH,
    MUXED_INPUT_PLAY_SWITCH,
    
    MUXED_INPUT_SWITCH_MAX = MUXED_INPUT_PLAY_SWITCH,
    MUXED_INPUT_MAX = MUXED_INPUT_SWITCH_MAX, /* 18 */
    
    MUXED_INPUT_N /* 19 */
};

enum muxed_outputs {
    MUXED_OUTPUT_MIN = 0, /* 0 */
    MUXED_OUTPUT_LEDS_MIN = MUXED_OUTPUT_MIN,
    /* LEDs. */
    MUXED_OUTPUT_STAR_L_LED = MUXED_OUTPUT_LEDS_MIN,
    MUXED_OUTPUT_TRIANGLE_L_LED,
    MUXED_OUTPUT_SQUARE_L_LED,
    MUXED_OUTPUT_HEART_L_LED,
    MUXED_OUTPUT_HEART_R_LED,
    MUXED_OUTPUT_SQUARE_R_LED,
    MUXED_OUTPUT_TRIANGLE_R_LED,
    MUXED_OUTPUT_STAR_R_LED,
    
    MUXED_OUTPUT_LEDS_MAX = MUXED_OUTPUT_STAR_R_LED, /* 7 */
    MUXED_OUTPUT_MAX = MUXED_OUTPUT_LEDS_MAX,
    
    MUXED_OUTPUT_N /* 8 */
};

typedef void (*muxed_inputs_on_changed_fn)(volatile bool (*)[MUXED_INPUT_N]);

void muxed_gpio_setup(muxed_inputs_on_changed_fn fn);
void muxed_gpio_set_output_levels(bool (*levels)[MUXED_OUTPUT_N]);
void muxed_gpio_get_input_switch_levels(bool (*levels)[MUXED_INPUT_N]);

#endif /* MUXED_GPIO_H */
